use_default_settings:
  engines:
    keep_only:
      - google
      - bing
server:
  limiter: false
  bind_address: 0.0.0.0
search:
  formats:
    - html
    - json
outgoing:
  request_timeout: 8.0
  max_request_timeout: 12.0
engines:
  - name: google
    disabled: false
  - name: bing
    disabled: false
